filterBlacklist: true
filterFunctions: [
  "Test.abs256(int256)",
  "Test.minmax(int128,int128)",
  "Test.muli(int128,int256)",
  "Test.debug(string,int128)",
  "Test.fromInt(int256)",
  "Test.toInt(int128)",
  "Test.fromUInt(uint256)",
  "Test.toUInt(int128)",
  "Test.from128x128(int256)",
  "Test.to128x128(int128)",
  "Test.add(int128,int128)",
  "Test.sub(int128,int128)",
  "Test.mul(int128,int128)",
  "Test.mulu(int128,uint256)",
  "Test.div(int128,int128)",
  "Test.divi(int128,int256)",
  "Test.divu(uint256,uint256)",
  "Test.neg(int128)",
  "Test.abs(int128)",
  "Test.inv(int128)",
  "Test.avg(int128,int128)",
  "Test.gavg(int128,int128)",
  "Test.pow(int128,uint256)",
  "Test.sqrt(int128)",
  "Test.log_2(int128)",
  "Test.ln(int128)",
  "Test.exp_2(int128)",
  "Test.exp(int128)"
]